// Annex H — Catalogue of Checks (Layer III, normative), as published in
// Document Management Standard v2 — condition, check method, evidence, clause,
// severity and owner transcribed from the Annex, not paraphrased.
// Identifier syntax: DEF-XX-nn. ▲ structural contradictions are Critical by definition.
// Severities and owners are fixed by the Annex, never assigned by the assessor (§17.2, §17.5).
// Owner codes: CF = designated control function · OR = originating party · RV = reviewer · OG = organization.

export type Severity = "CRITICAL" | "MAJOR" | "MINOR" | "ADVISORY";
export type OwnerCode = "CF" | "OR" | "RV" | "OG";
export type CheckDef = {
  id: string;
  condition: string;
  /** How the check detects the condition (Annex H "Check" column). */
  method: string;
  evidence: string;
  clause: string;
  severity: Severity;
  owner: OwnerCode;
  contradiction?: boolean; // ▲
};

const c = (id: string, condition: string, method: string, evidence: string, clause: string, severity: Severity, owner: OwnerCode, contradiction = false): CheckDef => ({
  id, condition, method, evidence, clause, severity, owner, contradiction,
});

export const FAMILY_TITLES: Record<string, string> = {
  IO: "H.0 The information object",
  ID: "H.1 Identity",
  MD: "H.2 Description",
  CL: "H.3 Classification",
  RV: "H.4 Revision",
  ST: "H.5 State and status",
  AP: "H.6 Approval",
  RO: "H.7 Review",
  FM: "H.8 Format",
  IS: "H.9 Issue and distribution",
  OB: "H.10 Obsolescence",
  RT: "H.11 Retention",
  DB: "H.12 Deliverable baseline",
  PK: "H.13 Packages",
  RG: "H.14 The register",
  SC: "H.15 Scope",
  CF: "H.15 Conformance",
};

export const CATALOG: CheckDef[] = [
  // ── DEF-IO (10)
  c("IO-01", "Controlled information in the declared sources has no register entry", "Compare the identified repositories, issue records and point-of-use inventory with the register; return each qualifying item with no entry", "Register + repository + audit trail", "§2.1", "CRITICAL", "OG"),
  c("IO-02", "Uncontrolled information circulated without the required marking", "Select and report the sample under §17.4; inspect each item that could be mistaken for controlled information", "File + transmittal record", "§2.1", "MAJOR", "OR"),
  c("IO-03", "Record treated as a document", "Records carrying revision values", "Register", "§2.2", "MAJOR", "CF"),
  c("IO-04", "Information treated as a record although a later occurrence replaces it", "For items classified as records, identify whether a later occurrence replaces the earlier one; return each item where only the latest remains valid", "Register + issue history", "§2.2", "MAJOR", "CF"),
  c("IO-05", "Confirmed record altered after confirmation", "Compare current content to change log", "Audit trail", "§2.3", "CRITICAL", "CF"),
  c("IO-06", "Correction issued with no reference to the record corrected", "Corrections with no relationship recorded", "Register", "§2.3", "MAJOR", "OR"),
  c("IO-07", "Record subjected to a Part that does not apply to it", "Find records with a revision value, release approval, review outcome, superseded state or deliverable-baseline obligation", "Register", "§2.4", "MINOR", "CF"),
  c("IO-08", "Defined reason set does not contain every required reason", "Confirm the published set covers the six reasons in §2.6", "authority instrument", "§2.6", "MAJOR", "OG"),
  c("IO-09", "Organization issue codes not mapped to the defined reasons", "Confirm the mapping is published", "authority instrument", "§2.6", "MAJOR", "OG"),
  c("IO-10", "Controlled terminology uses a defined term with another meaning", "Compare configured field labels and published value definitions with §0.4", "Configuration + authority instrument", "§0.4", "MINOR", "OG"),
  // ── DEF-ID (17)
  c("ID-01", "Document number absent", "Count records with a null number", "Register", "§3.1", "CRITICAL", "CF"),
  c("ID-02", "One number, two documents", "Count distinct titles per number", "Register", "§3.1", "CRITICAL", "CF", true),
  c("ID-03", "Number reused after cancellation", "Cancelled number appearing against a different title", "Register", "§3.1", "CRITICAL", "CF", true),
  c("ID-04", "Field count or order not per scheme", "Parse number against published structure", "Register + configuration", "§3.2", "MAJOR", "CF"),
  c("ID-05", "Delimiter appears within a field", "Split number; where segments exceed the published field count, rejoin adjacent segments and re-validate - a rejoin in which every field carries a published value indicates a delimiter within a value, otherwise an undefined additional field", "Register", "§3.2", "MAJOR", "CF"),
  c("ID-06", "Field value not in published set", "Compare each field to its value list", "Register + configuration", "§3.2", "MAJOR", "CF"),
  c("ID-07", "Required field absent from number", "Parse for project, discipline, type, sequence", "Register", "§3.3", "MAJOR", "CF"),
  c("ID-08", "Excluded value encoded in number", "Compare each part of the number to that document's own values in the register's changeable columns; flag a part matching one of those values where it is not a published code for its position", "Register", "§3.5", "MAJOR", "CF"),
  c("ID-09", "File name does not begin with the document number", "Compare the leading characters of the file name to the document number", "Audit trail + authoritative transmittal register", "§3.6", "MAJOR", "CF"),
  c("ID-10", "External item received without a number issued first", "Find the earliest transmittal across all revisions; count documents where the earliest sender is external. Establishes that no assignment is recorded before receipt, not that none was made", "System configuration + register + receipt record", "§3.7 · §16.8", "MAJOR", "CF"),
  c("ID-11", "Number outside any issued range", "Compare against range register", "Register", "§3.7", "CRITICAL", "CF", true),
  c("ID-12", "Legacy document not identified as such", "Pre-adoption records with no scheme marker", "Register", "§3.8", "MINOR", "CF"),
  c("ID-13", "Item produced with no register entry", "Repository files with no register record. Establishes that a file held in the repository has no entry, not that no item exists outside the repository", "Repository", "§3.9", "CRITICAL", "CF", true),
  c("ID-14", "Originator value not unique within the scope", "Count parties sharing an originator value", "Register + configuration", "§3.3", "MAJOR", "OG"),
  c("ID-15", "Party exchanging items without carrying the agreed number", "Count received items with no agreed number recorded. Establishes that no agreed number is recorded, not that the number carried differs from the one agreed", "Register", "§3.7", "MAJOR", "CF"),
  c("ID-16", "Renumbered item with no previous identifier retained", "Count migrated items with a null previous-identifier field", "Register", "§3.8", "MAJOR", "CF"),
  c("ID-17", "Additional field used but not published", "Compare fields in use to the published scheme", "Register + configuration", "§3.4", "MINOR", "OG"),
  // ── DEF-MD (17)
  c("MD-01", "Views issued in a form that can be edited independently of the system", "Confirm the system issues views that cannot be edited, or that a control used instead is published", "configuration + authority instrument", "§4.1", "MAJOR", "OG"),
  c("MD-02", "No authoritative register nominated", "Confirm nomination recorded", "configuration", "§4.1", "CRITICAL", "OG"),
  c("MD-03", "Derived value stored and disagreeing", "Compare stored to computed", "Register", "§4.2", "MAJOR", "CF"),
  c("MD-04", "Core document field empty on a released item", "Nulls in core fields where state is active", "Register", "§4.3", "CRITICAL", "OR"),
  c("MD-05", "Core revision field empty on a released revision", "Nulls where revision state is released", "Register", "§4.3", "CRITICAL", "OR"),
  c("MD-06", "Title generic or non-descriptive", "Match titles against excluded-term list", "Register", "§4.3", "MINOR", "OR"),
  c("MD-07", "Conditional field empty where deliverable type requires it", "Apply the type-to-field matrix", "Register + configuration", "§4.4", "MAJOR", "OR"),
  c("MD-08", "Filler value in a non-applicable field", "Search fields that do not apply for values in the published filler-value set", "Register + configuration", "§4.4", "MINOR", "OR"),
  c("MD-09", "Two recorded dates held in one field, or last updated entered manually", "Confirm four recorded date fields are distinct and last updated is derived", "configuration", "§4.5", "MAJOR", "CF"),
  c("MD-10", "Date received absent on an external deliverable type", "Nulls where type is external", "Register", "§4.5", "MAJOR", "CF"),
  c("MD-11", "Relationship recorded as a field", "Multi-valued entries in single-value fields", "Register", "§4.6", "MAJOR", "CF"),
  c("MD-12", "Action or package reference not retrievable from the item", "Query by action; compare to baseline", "Register", "§4.6", "CRITICAL", "CF", true),
  c("MD-13", "Value not in published set", "Compare each controlled field to its list", "Register + configuration", "§4.7", "MAJOR", "CF"),
  c("MD-14", "Value list unversioned", "Confirm version held", "configuration", "§4.7", "MINOR", "OG"),
  c("MD-15", "Value removed while still in use", "Compare list history to records in use", "configuration", "§4.7", "MAJOR", "OG"),
  c("MD-16", "Released with required conditional metadata empty", "Apply the type-to-field matrix to Released revisions", "Register + configuration", "§4.8", "CRITICAL", "OR", true),
  c("MD-17", "Metadata change not logged", "Compare current values to change-log coverage", "Audit trail", "§4.9", "MAJOR", "CF"),
  // ── DEF-CL (17)
  c("CL-01", "Two classifications in one field", "Search for composite values", "Register", "§5.1", "MAJOR", "CF"),
  c("CL-02", "Value of one classification held in another", "Cross-check values against each list", "Register", "§5.1", "MAJOR", "CF"),
  c("CL-03", "Deliverable type absent", "Count nulls", "Register", "§5.2", "CRITICAL", "OR"),
  c("CL-04", "Deliverable type changed after creation", "Compare change log to creation value", "Audit trail", "§5.2", "CRITICAL", "CF", true),
  c("CL-05", "Type-to-field matrix not published", "Confirm publication", "authority instrument", "§5.2", "CRITICAL", "OG"),
  c("CL-06", "Document type absent or not in set", "Nulls and off-list values", "Register", "§5.3", "MAJOR", "OR"),
  c("CL-07", "Document type changed after creation", "Compare change log", "Audit trail", "§5.3", "MINOR", "CF"),
  c("CL-08", "Discipline absent", "Count nulls", "Register", "§5.4", "MAJOR", "OR"),
  c("CL-09", "More than one discipline held", "Count multi-valued entries", "Register", "§5.4", "MAJOR", "CF"),
  c("CL-10", "Phase held at document level", "Confirm phase resides on the revision", "configuration", "§5.5", "MAJOR", "CF"),
  c("CL-11", "Criticality absent where classification is in use", "Count nulls", "Register", "§5.6", "MAJOR", "OR"),
  c("CL-12", "Criticality-to-control rules not published for approval, retention or format", "Confirm each criticality class has published approval, retention and format consequences", "authority instrument", "§5.6", "CRITICAL", "OG", true),
  c("CL-13", "Confidentiality absent and no default published", "Confirm default published", "authority instrument", "§5.7", "MAJOR", "OG"),
  c("CL-14", "Access does not match confidentiality", "Compare access rights to classification", "configuration", "§5.7", "CRITICAL", "OG", true),
  c("CL-15", "Confidentiality changed without access adjusted", "Compare change log to access log dates", "Audit trail", "§5.7", "MAJOR", "CF"),
  c("CL-16", "Item not associated with any asset item", "Records with no association where required", "Register", "§5.8", "MAJOR", "OR"),
  c("CL-17", "Information not retrievable by asset item", "Query by asset item; count items returning no documents", "Register", "§5.8", "MAJOR", "CF"),
  // ── DEF-RV (16)
  c("RV-01", "Version issued as if a revision", "Issued records with no revision value", "Register", "§6.1", "MAJOR", "OR"),
  c("RV-02", "Scheme not published", "Confirm publication", "authority instrument", "§6.2", "CRITICAL", "OG"),
  c("RV-03", "Revision not in the applicable series", "Compare value to series and transition point", "Register", "§6.2", "MAJOR", "CF"),
  c("RV-04", "Excluded character used", "Search values for I, O, Q, S, X, Z", "Register", "§6.2", "MINOR", "CF"),
  c("RV-05", "Two schemes running concurrently", "Count distinct scheme patterns in scope", "Register", "§6.2", "MAJOR", "OG"),
  c("RV-06", "Revision sequence moving backwards", "Order revisions by issue date; check monotonicity", "Register", "§6.3", "CRITICAL", "CF", true),
  c("RV-07", "Revision value repeated within a document", "Count duplicate values per document", "Register", "§6.3", "CRITICAL", "CF", true),
  c("RV-08", "More than one revision in preparation", "Count per document where state is in preparation", "Register", "§6.3", "MAJOR", "CF"),
  c("RV-09", "Revision encoded in the document number", "Parse number for a revision pattern", "Register", "§6.4", "MAJOR", "CF"),
  c("RV-10", "Revision established with no authorization", "Revisions with no authorization record", "Register", "§6.5", "CRITICAL", "CF", true),
  c("RV-11", "Authorization missing reason, party or date", "Count incomplete authorization records", "Register", "§6.5", "MAJOR", "CF"),
  c("RV-12", "Revision submitted without authorization issued", "Compare submission to authorization dates", "Register", "§6.5", "MAJOR", "OR"),
  c("RV-13", "Reason for revision absent", "Count nulls", "Register", "§6.6", "MAJOR", "OR"),
  c("RV-14", "Description of change absent or restating the reason", "Count nulls, and rows where the description equals the reason", "Register", "§6.6", "MINOR", "OR"),
  c("RV-15", "Two current revisions of one document", "Released, unsuperseded revisions per document", "Register", "§6.7", "CRITICAL", "CF", true),
  c("RV-16", "Document in use with no current revision", "Active documents with no released revision", "Register", "§6.7", "CRITICAL", "CF", true),
  // ── DEF-ST (14)
  c("ST-01", "State held at document level only", "Confirm state exists on revisions", "configuration", "§7.1", "MAJOR", "CF"),
  c("ST-02", "Revision state not in the permitted set", "Compare to §7.2", "Register", "§7.2", "MAJOR", "CF"),
  c("ST-03", "Document state not in the permitted set", "Compare to §7.3", "Register", "§7.3", "MAJOR", "CF"),
  c("ST-04", "More than one state held", "Count state assignments per record", "Register", "§7.4", "CRITICAL", "CF", true),
  c("ST-05", "State absent", "Count nulls", "Register", "§7.4", "CRITICAL", "CF"),
  c("ST-06", "Backward state transition", "Order transitions; check direction", "Audit trail", "§7.5", "CRITICAL", "CF", true),
  c("ST-07", "First revision released but document not moved to Active", "Compare first release to document-state transition", "Register", "§7.3 · §7.5", "CRITICAL", "CF", true),
  c("ST-08", "Earlier revision still released after its successor", "Count released revisions per document", "Register", "§7.5", "CRITICAL", "CF", true),
  c("ST-09", "Released revision carrying no status", "Nulls where state is released", "Register", "§7.6", "CRITICAL", "CF"),
  c("ST-10", "Status set not published", "Confirm publication", "authority instrument", "§7.7", "CRITICAL", "OG"),
  c("ST-11", "Status not in the published set", "Compare values to list", "Register + configuration", "§7.7", "MAJOR", "CF"),
  c("ST-12", "Execution statuses not identified", "Confirm an execution flag on each value", "configuration", "§7.8", "CRITICAL", "OG"),
  c("ST-13", "Execution proceeding on a non-execution status", "Compare action records to item status", "Register", "§7.8", "CRITICAL", "OG", true),
  c("ST-14", "Transition not logged with actor and time", "Transitions with incomplete log entries", "Audit trail", "§7.9", "MAJOR", "CF"),
  // ── DEF-AP (13)
  c("AP-01", "Released with no approval", "Released revisions with no approval record", "Register", "§8.1", "CRITICAL", "CF", true),
  c("AP-02", "Authority matrix not published", "Confirm publication", "authority instrument", "§8.2", "CRITICAL", "OG"),
  c("AP-03", "Matrix unversioned, or version not identifiable at the approval date", "Confirm version history held", "authority instrument", "§8.2", "MAJOR", "OG"),
  c("AP-04", "Approval attributed to a role, not a person", "Approvals with no named individual", "Register", "§8.3", "CRITICAL", "CF"),
  c("AP-05", "Approver held no authority for that class at that time", "Compare approver to the matrix version in force", "Register + authority instrument", "§8.3", "CRITICAL", "CF", true),
  c("AP-06", "Approval evidence not retained", "Approvals with no evidence held", "Repository", "§8.4", "CRITICAL", "CF"),
  c("AP-07", "Approval on the document face not recorded as metadata", "Compare rendition to register", "File + register", "§8.4", "MAJOR", "CF"),
  c("AP-08", "Delegation with no end date", "Count open-ended delegations", "authority instrument", "§8.5", "MAJOR", "OG"),
  c("AP-09", "Approval under an expired delegation", "Compare approval date to delegation period", "Register + authority instrument", "§8.5", "CRITICAL", "CF", true),
  c("AP-10", "Onward delegation recorded", "Delegations whose grantor holds delegated authority", "authority instrument", "§8.5", "MAJOR", "OG"),
  c("AP-11", "Criticality not reflected in the authority applied", "Compare criticality to approver authority", "Register", "§8.6", "MAJOR", "OG"),
  c("AP-12", "Withdrawal not recorded with reason and authority", "Count incomplete withdrawal records", "Register", "§8.7", "MAJOR", "CF"),
  c("AP-13", "Approval withdrawn but document not withdrawn", "Compare withdrawal records to document state", "Register", "§8.7", "CRITICAL", "CF", true),
  // ── DEF-RO (18)
  c("RO-01", "Review cycle not held as a record", "Confirm cycle records exist with their own identity", "Register", "§9.1", "CRITICAL", "CF"),
  c("RO-02", "Review-cycle event timestamp missing", "Cycles with incomplete event records", "Register", "§9.1", "MAJOR", "CF"),
  c("RO-03", "Outcome set not published", "Confirm publication", "authority instrument", "§9.2", "CRITICAL", "OG"),
  c("RO-04", "Outcome not in the published set", "Compare values to list", "Register + configuration", "§9.2", "MAJOR", "CF"),
  c("RO-05", "Outcome carrying no proceed consequence", "Confirm mapping for each value", "configuration", "§9.3", "CRITICAL", "OG"),
  c("RO-06", "Outcome carrying no resubmission consequence", "Confirm mapping for each value", "configuration", "§9.3", "CRITICAL", "OG"),
  c("RO-07", "Resubmission required but no revision authorized", "Compare outcomes to authorization records", "Register", "§9.3", "CRITICAL", "CF", true),
  c("RO-08", "More than one outcome on a cycle", "Count outcomes per cycle", "Register", "§9.4", "CRITICAL", "CF", true),
  c("RO-09", "Outcome altered after recording", "Compare to change log", "Audit trail", "§9.4", "CRITICAL", "CF"),
  c("RO-10", "Outcome held only in an attachment", "Cycles with a null outcome field", "Register", "§9.5", "CRITICAL", "CF"),
  c("RO-11", "Comment with no progression consequence recorded", "Count unclassified comments", "Register", "§9.6", "MAJOR", "RV"),
  c("RO-12", "Progression-preventing comment with no recorded resolution state", "Nulls in status", "Register", "§9.6", "MAJOR", "RV"),
  c("RO-13", "Progression-preventing comment closed with no recorded response", "Closures with no response", "Register", "§9.6", "MAJOR", "RV"),
  c("RO-14", "Work proceeding with a progression-preventing comment open", "Compare action records to open comments", "Register", "§9.6", "CRITICAL", "OG", true),
  c("RO-15", "Review sequence not set before the cycle began", "Compare sequence record to cycle start", "Register", "§9.7", "MINOR", "CF"),
  c("RO-16", "Separate outcomes issued for one cycle instead of one consolidated outcome", "Count issuing parties and consolidated outcomes per cycle", "Register", "§9.7", "MAJOR", "CF"),
  c("RO-17", "Reviewer sent an outcome directly to the originator", "Compare outcome route to the return records", "Audit trail", "§9.8", "MAJOR", "RV"),
  c("RO-18", "Completed cycle not returned to the designated control function", "Compare completed cycles to control-function return records", "Audit trail", "§9.8", "MAJOR", "RV"),
  // ── DEF-FM (11)
  c("FM-01", "Native form not retained", "Released revisions with no native file", "Repository", "§10.1", "MAJOR", "OR"),
  c("FM-02", "Application and version not recorded for a proprietary format", "Count nulls", "Register", "§10.1", "MINOR", "OG"),
  c("FM-03", "Released revision with no rendition", "Count nulls", "Repository", "§10.2", "CRITICAL", "CF"),
  c("FM-04", "Rendition in a format requiring the authoring application", "Compare format to published list", "File", "§10.2", "MAJOR", "CF"),
  c("FM-05", "Rendition not showing number, revision, status and date", "Inspect a published sample; count items lacking the marking", "File", "§10.2", "MAJOR", "OR"),
  c("FM-06", "Native and rendition are different revisions", "Compare revision identifiers", "Repository + file", "§10.3", "CRITICAL", "CF", true),
  c("FM-07", "Rendition not reproduced after a revision change", "Compare rendition date to revision date", "Repository", "§10.3", "MAJOR", "CF"),
  c("FM-08", "Long-term retention in a non-preservation format", "Compare format to published list where retention exceeds the project", "File", "§10.4", "MAJOR", "OG"),
  c("FM-09", "Preservation formats not published", "Confirm publication", "authority instrument", "§10.4", "MAJOR", "OG"),
  c("FM-10", "File missing or unreadable", "Retrieve a published sample; count retrieval failures", "Repository + file", "§10.5", "CRITICAL", "CF"),
  c("FM-11", "File altered since release", "Compare integrity check to release record", "File + audit trail", "§10.5", "CRITICAL", "CF"),
  // ── DEF-IS (30)
  c("IS-01", "Information issued with no transmittal", "Compare issue records to transmittal records", "Register", "§11.1", "CRITICAL", "CF", true),
  c("IS-02", "Transmittal number absent or reused", "Nulls and duplicates", "Register", "§11.1", "MAJOR", "CF"),
  c("IS-03", "Transmittal missing a required element", "Count incomplete transmittals", "Register", "§11.1", "MAJOR", "CF"),
  c("IS-04", "Reason for issue absent", "Count nulls", "Register", "§11.2", "MAJOR", "CF"),
  c("IS-05", "Reason for issue not in the defined set", "Compare to set", "Register + configuration", "§11.2", "MAJOR", "CF"),
  c("IS-06", "Unreleased revision issued for current use", "Compare current-use issues to revision state, excluding a requested historical issue marked Superseded", "Register", "§11.3", "CRITICAL", "CF", true),
  c("IS-07", "Issued at a status higher than recorded", "Compare transmittal status to revision status", "Register", "§11.3", "CRITICAL", "CF", true),
  c("IS-08", "Superseded revision issued without being marked as such", "Compare issue date to supersession date", "Register", "§11.3", "MAJOR", "CF"),
  c("IS-09", "Recipients recorded only as a group or role", "Transmittals with no named individuals", "Register", "§11.4", "MAJOR", "CF"),
  c("IS-10", "Receipt not recorded where a consequence follows", "Transmittals requiring response with no receipt", "Register", "§11.5", "MAJOR", "CF"),
  c("IS-11", "Receipt date earlier than issue date", "Compare dates", "Register", "§11.5", "MAJOR", "CF"),
  c("IS-12", "Copy issued and not registered", "Compare download or print log to copy register", "Audit trail", "§11.6", "MAJOR", "CF"),
  c("IS-13", "Registered copy with no holder or location", "Count incomplete entries", "Register", "§11.6", "MAJOR", "CF"),
  c("IS-14", "Copy not marked uncontrolled where unregistered", "Inspect a published sample; count items lacking the marking", "File", "§11.6", "MINOR", "CF"),
  c("IS-15", "Reviewed information returned outside the control function", "Compare return route to the return records", "Audit trail", "§11.7", "MAJOR", "RV"),
  c("IS-16", "Required revision authorization not issued with an outcome requiring resubmission", "Compare resubmission outcomes to returned authorizations", "Register", "§11.7", "MAJOR", "CF"),
  c("IS-17", "Distribution rules not published", "Confirm publication", "authority instrument", "§11.8", "MAJOR", "OG"),
  c("IS-18", "Issue outside defined distribution with no reason recorded", "Compare recipients to rules", "Register", "§11.8", "MINOR", "CF"),
  c("IS-19", "Transmittal content not matching its list", "Compare enclosed to listed", "Repository", "§11.9", "MAJOR", "OR"),
  c("IS-20", "Rejection not recorded with a reason", "Rejections with a null reason", "Register", "§11.9", "MAJOR", "CF"),
  c("IS-21", "Rejected transmittal handled otherwise than the published consequence", "Compare handling to the published rule", "Register", "§11.9", "MAJOR", "CF"),
  c("IS-22", "Rejection consequence not published", "Confirm publication", "authority instrument", "§11.10", "CRITICAL", "OG"),
  c("IS-23", "Rejected transmittal not retained", "Rejections with no record held", "Register", "§11.10", "MINOR", "CF"),
  c("IS-24", "Review cycle with no originating transmittal, external origin", "Compare cycles to transmittals by deliverable type", "Register", "§11.11", "MAJOR", "CF"),
  c("IS-25", "Transmittal carrying several items held as one cycle", "Count cycles per transmittal against items carried", "Register", "§11.11", "MAJOR", "CF"),
  c("IS-26", "Acceptance or response periods not published", "Confirm publication", "authority instrument", "§11.12", "MAJOR", "OG"),
  c("IS-27", "Transmittal not checked within the acceptance period", "Compare acceptance date to receipt date", "Register", "§11.12", "MAJOR", "CF"),
  c("IS-28", "Response period measured from receipt, not acceptance", "Compare period start to acceptance date", "Register", "§11.12", "MAJOR", "CF"),
  c("IS-29", "Information crossing a boundary without passing the control function", "Compare transmittal records to external correspondence", "Audit trail", "§11.13", "MAJOR", "OG"),
  c("IS-30", "Transmittal raised for internal movement", "Transmittals with no external party", "Register", "§11.13", "MINOR", "CF"),
  // ── DEF-OB (15)
  c("OB-01", "End state not recorded with date and authority", "Count incomplete records", "Register", "§12.1", "MAJOR", "CF"),
  c("OB-02", "Superseded and void used interchangeably", "Compare void records to supersession records", "Register", "§12.1", "MAJOR", "CF"),
  c("OB-03", "Obsolete information issued or made available", "Compare issue records to state at the issue date", "Register", "§12.2", "CRITICAL", "CF", true),
  c("OB-04", "Withdrawn or void item still in use", "Compare action records to item state", "Register", "§12.2", "CRITICAL", "OG", true),
  c("OB-05", "Supersession, withdrawal or voiding with no notification issued", "Compare invalidation records to notifications", "Register", "§12.3", "CRITICAL", "CF", true),
  c("OB-06", "Notification missing item, revision, reason or replacement", "Count incomplete notifications", "Register", "§12.3", "MAJOR", "CF"),
  c("OB-07", "Notification not reaching all historical recipients", "Compare notification recipients to issue history", "Register", "§12.3", "MAJOR", "CF"),
  c("OB-08", "Registered copy carrying an invalid revision, no action recorded", "Compare copy register to revision states", "Register", "§12.4", "CRITICAL", "CF", true),
  c("OB-09", "Copy action not recorded", "Entries with no action", "Register", "§12.4", "MAJOR", "CF"),
  c("OB-10", "Obsolete rendition not visibly marked", "Inspect a published sample; count items lacking the marking", "File", "§12.5", "MAJOR", "CF"),
  c("OB-11", "Obsolete revision returned in ordinary search", "Search for the current document; count results returning obsolete revisions", "configuration", "§12.5", "MAJOR", "CF"),
  c("OB-12", "Obsolete information held indistinguishably from current", "Compare storage or state marking", "Repository", "§12.5", "MAJOR", "CF"),
  c("OB-13", "Void revision with no reassessment of work performed", "Compare void records to reassessment records", "Register", "§12.6", "CRITICAL", "OG", true),
  c("OB-14", "Item withdrawn while an open action requires it", "Compare baseline entries to item state", "Register", "§12.6", "CRITICAL", "CF", true),
  c("OB-15", "Exposure conditions not reportable", "Attempt each query in §12.6", "Register", "§12.6", "CRITICAL", "CF"),
  // ── DEF-RT (15)
  c("RT-01", "Retention schedule not published", "Confirm publication", "authority instrument", "§13.1", "CRITICAL", "OG"),
  c("RT-02", "Retention basis not stated for a class", "Classes with no basis", "authority instrument", "§13.1", "MAJOR", "OG"),
  c("RT-03", "Schedule unversioned", "Confirm version held", "authority instrument", "§13.1", "MINOR", "OG"),
  c("RT-04", "Retention class absent", "Count nulls", "Register", "§13.2", "MAJOR", "OR"),
  c("RT-05", "Item retention class does not match the published criticality rule", "Compare assigned class to the criticality-to-retention mapping", "Register + authority instrument", "§13.2", "MINOR", "OG"),
  c("RT-06", "Retention start event not recorded", "Records with no start event", "Register", "§13.3", "MAJOR", "CF"),
  c("RT-07", "Retention treated as expired before its event occurred", "Compare disposal records to start events", "Register", "§13.3", "CRITICAL", "OG", true),
  c("RT-08", "Archived information not retrievable", "Retrieve a published sample from archive; count failures", "Repository", "§13.4", "CRITICAL", "CF"),
  c("RT-09", "Archived information without metadata or register entry", "Compare archive to register", "Register + repository", "§13.4", "CRITICAL", "CF", true),
  c("RT-10", "Information removed from the register on archiving", "Archived records absent from register", "Register", "§13.4", "CRITICAL", "CF"),
  c("RT-11", "Disposal before the retention period expired", "Compare disposal dates to periods", "Register", "§13.5", "CRITICAL", "OG", true),
  c("RT-12", "Disposal not authorized or not recorded", "Disposals with incomplete records", "Register", "§13.5", "CRITICAL", "OG"),
  c("RT-13", "Disposal of information under legal hold", "Compare disposal records to the hold register", "Register", "§13.5", "CRITICAL", "OG", true),
  c("RT-14", "Register entry removed on disposal", "Disposed records absent from register", "Register", "§13.5", "MAJOR", "CF"),
  c("RT-15", "Retention classes not aligned to records classification where one exists", "Compare schedules", "authority instrument", "§13.6", "MINOR", "OG"),
  // ── DEF-DB (13)
  c("DB-01", "No baseline agreed for a scope requiring one", "Confirm baseline exists and is agreed", "Register", "§14.1", "CRITICAL", "OG"),
  c("DB-02", "Action code absent or reused", "Nulls and duplicates", "Register", "§14.2", "MAJOR", "OG"),
  c("DB-03", "Action not derived from the schedule", "Compare action codes to schedule", "Register", "§14.2", "MAJOR", "OG"),
  c("DB-04", "Baseline entry missing a required field", "Count incomplete entries", "Register", "§14.3", "MAJOR", "CF"),
  c("DB-05", "Item required by several actions held as one entry", "Count entries per item-action pair", "Register", "§14.3", "MAJOR", "CF"),
  c("DB-06", "Required-by date not derived from the action date", "Compare dates against lead time", "Register", "§14.4", "MAJOR", "CF"),
  c("DB-07", "Information not retrievable by action code", "Query by action", "Register", "§14.5", "MAJOR", "CF"),
  c("DB-08", "Action references on the item disagreeing with the baseline", "Compare both directions", "Register", "§14.5", "CRITICAL", "CF", true),
  c("DB-09", "Action date changed without formal issue", "Compare schedule changes to issue records", "Audit trail", "§14.6", "MAJOR", "OG"),
  c("DB-10", "Baseline date disagreeing with the schedule date", "Compare baseline to current schedule", "Register", "§14.6", "CRITICAL", "CF", true),
  c("DB-11", "Baseline change without recorded approval", "Changes with no approval", "Register", "§14.7", "MAJOR", "OG"),
  c("DB-12", "Baseline change history not retained", "Confirm history held", "Register", "§14.7", "MAJOR", "CF"),
  c("DB-13", "Action proceeded without readiness verification", "Compare action records to verification records", "Register", "§14.8", "CRITICAL", "OG", true),
  // ── DEF-PK (15)
  c("PK-01", "Package type not stated", "Count nulls", "Register", "§15.1", "MAJOR", "OG"),
  c("PK-02", "Defined package with no agreed composition", "Packages with no member list", "Register", "§15.2", "CRITICAL", "OG"),
  c("PK-03", "Accumulated package with no membership rule stated", "Packages with no rule", "Register", "§15.2", "CRITICAL", "OG"),
  c("PK-04", "Package attribute absent", "Count incomplete package records", "Register", "§15.3", "MAJOR", "OG"),
  c("PK-05", "Package membership held as an item field", "Count multi-valued entries", "Register", "§15.4", "MAJOR", "CF"),
  c("PK-06", "Composition owner not assigned", "Count nulls", "Register", "§15.5", "MAJOR", "OG"),
  c("PK-07", "Acceptance authority the same as the composition owner", "Compare the two", "Register", "§15.5", "CRITICAL", "OG", true),
  c("PK-08", "Package not assessed at its completion date", "Compare assessment records to dates", "Register", "§15.6", "MAJOR", "CF"),
  c("PK-09", "Shortfall not recorded for an incomplete package", "Incomplete packages with no shortfall record", "Register", "§15.7", "MAJOR", "OG"),
  c("PK-10", "Shortfall not issued to the acceptance authority", "Compare issue records to assessment", "Register", "§15.7", "MAJOR", "CF"),
  c("PK-11", "Package closed with an unresolved, unaccepted shortfall", "Compare closures to shortfall and acceptance records", "Register", "§15.8", "CRITICAL", "OG", true),
  c("PK-12", "Accumulated package closed without stating the rule ceased", "Closures with no rule statement", "Register", "§15.8", "MINOR", "OG"),
  c("PK-13", "Package containing another package", "Count nested memberships", "Register", "§15.9", "MAJOR", "CF"),
  c("PK-14", "Reason for issue not stated", "Count nulls", "Register", "§15.1", "MAJOR", "OG"),
  c("PK-15", "Package issued under a reason different from its recorded purpose", "Compare package purpose to the issue reason", "Register", "§15.1", "MAJOR", "CF"),
  // ── DEF-RG (17)
  c("RG-01", "No register maintained for a scope", "Confirm register exists", "Register", "§16.1", "CRITICAL", "OG"),
  c("RG-02", "Register maintained separately from the source of truth", "Compare register to system", "Register + configuration", "§16.1", "CRITICAL", "CF"),
  c("RG-03", "Controlled information absent from the register", "Compare repository to register", "Repository", "§16.2", "CRITICAL", "CF"),
  c("RG-04", "Item removed from register to record disuse", "Compare removals to state changes", "Audit trail", "§16.2", "MAJOR", "CF"),
  c("RG-05", "Required record type not held with independent identity", "Confirm each applicable record type exists", "configuration", "§16.3", "CRITICAL", "CF"),
  c("RG-06", "Multiple occurrences collapsed into one row", "Count occurrences held per parent record", "Register", "§16.3", "MAJOR", "CF"),
  c("RG-07", "An applicable question in §16.4 is unanswerable without manual work", "Attempt each applicable question", "Register", "§16.4", "MAJOR", "CF"),
  c("RG-08", "Register entry with no file held, other than a planned item", "Compare register to repository, excluding planned state", "Register + repository", "§16.5", "CRITICAL", "CF", true),
  c("RG-09", "File held with no register entry", "Compare repository to register", "Repository", "§16.5", "CRITICAL", "CF", true),
  c("RG-10", "Register current revision differing from the file held", "Compare revision identifiers", "Register + repository", "§16.5", "CRITICAL", "CF", true),
  c("RG-11", "Extract without a generation timestamp", "Inspect a published sample; count items lacking the marking", "File", "§16.6", "MINOR", "CF"),
  c("RG-12", "Extract circulated in place of register access", "Compare distribution records to access provision", "Audit trail", "§16.6", "MINOR", "OG"),
  c("RG-13", "Register not retained beyond the project", "Confirm retention arrangement", "authority instrument", "§16.7", "CRITICAL", "OG"),
  c("RG-14", "Register not transferable independently of its system", "Attempt export with metadata", "configuration", "§16.7", "MAJOR", "OG"),
  c("RG-15", "Agreed deliverable with no placeholder entry", "Compare agreed lists to register", "Register", "§16.8", "MAJOR", "CF"),
  c("RG-16", "Entry still identified as a placeholder after its first revision is established", "Find placeholder flags on entries holding a revision", "Register", "§16.8", "CRITICAL", "CF", true),
  c("RG-17", "Register not discoverable to parties within scope", "Confirm access", "configuration", "§16.9", "MAJOR", "OG"),
  // ── DEF-SC (13)
  c("SC-01", "Scope not stated", "Confirm statement recorded", "authority instrument", "§1.2", "CRITICAL", "OG"),
  c("SC-02", "Scope changed during execution", "Compare to initiation record", "authority instrument", "§1.2", "MAJOR", "OG"),
  c("SC-03", "Local configuration incomplete", "Confirm every item in Annex C published", "authority instrument", "§1.3", "CRITICAL", "OG"),
  c("SC-04", "Requirement with no owner assigned", "Count unassigned requirements", "authority instrument", "§1.4", "CRITICAL", "OG"),
  c("SC-05", "Owner assigned to an individual, not a role", "Count individual assignments", "authority instrument", "§1.4", "MINOR", "OG"),
  c("SC-06", "Assessment statement claims conformance at clause level", "Confirm the statement names a level and does not cite individual clauses", "authority instrument", "§1.5", "MINOR", "OG"),
  c("SC-07", "Departure required by contract or regulation not recorded", "Compare applied practice to the Standard", "authority instrument", "§1.8", "MAJOR", "OG"),
  c("SC-08", "Silence treated as a conflict", "Count departures citing a requirement the other instrument does not address", "authority instrument", "§1.8", "MINOR", "OG"),
  c("SC-09", "Effective date not stated", "Confirm statement recorded", "authority instrument", "§1.9", "CRITICAL", "OG"),
  c("SC-10", "Running project with no migration position recorded", "Projects in scope with no position", "authority instrument", "§1.9", "MAJOR", "OG"),
  c("SC-11", "Exemption or exception not recorded as required", "Compare transition exemptions and exception-register entries to §§1.9 and 1.10", "authority instrument", "§1.9 · §1.10", "MAJOR", "OG"),
  c("SC-12", "Assessment statement missing a required identifying element", "Confirm all six elements of §1.6 are present", "authority instrument", "§1.6", "MAJOR", "OG"),
  c("SC-13", "Statement issued without the checks having been applied", "Compare statement date to recorded check results", "Audit trail", "§1.6", "CRITICAL", "OG"),
  // ── DEF-CF (23)
  c("CF-01", "Full-population check not applied to the full declared scope", "Compare records checked to scope", "Audit trail", "§17.1", "MAJOR", "OG"),
  c("CF-02", "Control-integrity denominator excludes controlled items within the declared scope", "Compare denominator to the declared-scope population", "Register", "§17.1 · §17.4", "MAJOR", "OG"),
  c("CF-03", "Severity assigned at assessment", "Compare applied severity to this Annex", "Audit trail", "§17.2", "MAJOR", "OG"),
  c("CF-04", "Severity varying between assessments", "Compare across measurements", "Audit trail", "§17.2", "MAJOR", "OG"),
  c("CF-05", "Structural contradiction not contained, corrected and rerun", "For each contradiction, confirm containment, correction, impact assessment and successful rerun", "Register + audit trail", "§17.3", "CRITICAL", "CF"),
  c("CF-06", "Integrity stated without scope, date, version and counts", "Confirm the statement carries scope, date, version, counts and scope-level findings", "authority instrument", "§17.4", "MAJOR", "OG"),
  c("CF-07", "Integrity weighted or adjusted", "Compare stated figure to raw calculation", "Audit trail", "§17.4", "CRITICAL", "OG"),
  c("CF-08", "Critical defects omitted from the statement", "Compare statement to check results", "Audit trail", "§17.4", "CRITICAL", "OG"),
  c("CF-09", "Defect recorded with no owner", "Count unassigned defects", "Register", "§17.5", "MAJOR", "CF"),
  c("CF-10", "External-origin defect not raised with the party", "Compare defect records to notifications", "Register", "§17.5", "MAJOR", "CF"),
  c("CF-11", "Closure recorded while the check still returns the item", "Re-run check on closed defects", "Register", "§17.6", "CRITICAL", "CF", true),
  c("CF-12", "Accepted defect not counted", "Compare counts to acceptance records", "Audit trail", "§17.6", "MAJOR", "OG"),
  c("CF-13", "Accepted defect with no review date", "Acceptances with a null review date", "Register", "§17.6", "MINOR", "OG"),
  c("CF-14", "Statement drawn from the register with no current measurement", "Compare report dates to measurement dates", "Audit trail", "§17.7", "MAJOR", "OG"),
  c("CF-15", "Performance figure issued without control integrity and open Critical count", "Count reports issued without the control integrity figure and open Critical count", "Audit trail", "§17.7", "MAJOR", "OG"),
  c("CF-16", "Conformance not measured before an assessment statement, handover or configuration change", "Compare measurement dates to events", "Audit trail", "§17.8", "MAJOR", "OG"),
  c("CF-17", "Trend across measurements not identifiable", "Confirm results retained", "Audit trail", "§17.8", "MINOR", "OG"),
  c("CF-18", "Non-conformance not recorded, assigned or reported in the statement", "Compare check results to the recorded findings and the statement", "Register + authority instrument", "§1.7", "MAJOR", "CF"),
  c("CF-19", "Sampled check incorporated into the control integrity figure", "Compare calculation inputs to per-check population coverage", "Audit trail", "§17.4", "CRITICAL", "OG"),
  c("CF-20", "Sampled check reported without its population, sample unit, selection method, sample size, assessment date or failure rate", "Confirm sampled-check reporting elements", "authority instrument + audit trail", "§17.4", "MAJOR", "OG"),
  c("CF-21", "Normative Rule has no linked Check", "List normative Rule IDs absent from Traceability Spine Check links", "Traceability Spine + baseline", "F.3 · F.5", "CRITICAL", "CF"),
  c("CF-22", "Changed Rule has an unreviewed linked Route or Check", "Compare Rule version changes to linked relationship states", "Traceability Spine + change log", "F.4 · F.5", "CRITICAL", "CF"),
  c("CF-23", "Synchronized baseline issued with a version mismatch, Gap or Review required state", "Identify unresolved or version-mismatched links at release", "Traceability Spine + release record", "F.5", "MAJOR", "OG"),
];

export const CHECK_BY_ID = new Map(CATALOG.map((c) => [c.id, c]));
export const FAMILIES = [...new Set(CATALOG.map((c) => c.id.split("-")[1]))];
