apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Alertmanager
    uid: alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus
