import { NextResponse } from "next/server";
import { getScope } from "@/lib/scope";
import { getSessionUser } from "@/lib/auth";

// §16.6 — a view: generated at time of use, carries generation date/time,
// never edited. The flat document list is a view of the register (§16.1).
export async function GET(request: Request) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const ctx = await getScope();
  if (!ctx) return NextResponse.json({ error: "No active project" }, { status: 403 });
  const { db } = ctx;

  const params = new URL(request.url).searchParams;
  const ids = (params.get("ids") ?? "").split(",").map((value) => value.trim()).filter(Boolean);
  const q = (params.get("q") ?? "").trim();
  const state = params.get("state") ?? "";
  const discipline = params.get("discipline") ?? "";
  const docType = params.get("docType") ?? "";

  const docs = await db.document.findMany({
    where: {
      AND: [
        ids.length ? { id: { in: ids } } : {},
        q ? { OR: [{ docNumber: { contains: q } }, { title: { contains: q } }, { originator: { contains: q } }, { contractRef: { contains: q } }] } : {},
        state ? { state } : {}, discipline ? { discipline } : {}, docType ? { docType } : {},
      ],
    },
    orderBy: { docNumber: "asc" },
    include: {
      revisions: { orderBy: { createdAt: "desc" }, include: { workflowRuns: { orderBy: { updatedAt: "desc" }, take: 1 }, approvals: { where: { withdrawnAt: null }, orderBy: { decidedAt: "desc" }, take: 1 } } },
      _count: { select: { baselineEntries: true, packageMembers: true } },
    },
  });

  const stamp = new Date();
  const rows: string[][] = [
    ["Generated at", stamp.toISOString()],
    ["Generated by", user.email],
 ["Scope", "All states — the register holds every item irrespective of state"],
    [],
    ["Document number", "Title", "Deliverable type", "Document type", "Discipline", "Originator", "Sub-project", "Contract / PO", "Criticality", "Confidentiality", "Retention class", "Document state", "Placeholder", "Previous identifier", "Legacy scheme", "Created date", "Received date", "Authoring application", "Latest revision", "Latest revision state", "Current revision", "Current status", "Planned submission", "Issue date", "Released at", "Approval by", "Workflow", "Workflow state", "Schedule links", "Package memberships", "Last updated"],
  ];
  for (const d of docs) {
    const current = d.revisions.find((r) => r.state === "RELEASED");
    const latest = d.revisions[0];
    const run = d.revisions.flatMap((revision) => revision.workflowRuns).find((workflow) => workflow.status === "ACTIVE") ?? latest?.workflowRuns[0];
    const approval = latest?.approvals[0];
    rows.push([
      d.docNumber, d.title, d.deliverableType, d.docType, d.discipline, d.originator ?? "", d.subProject ?? "", d.contractRef ?? "",
      d.criticality ?? "", d.confidentiality ?? "", d.retentionClass ?? "", d.state, d.isPlaceholder ? "yes" : "no", d.previousId ?? "", d.legacyScheme ?? "",
      d.createdDate.toISOString(), d.receivedDate?.toISOString() ?? "", d.appVersion ?? "", latest?.value ?? "", latest?.state ?? "",
      current?.value ?? "", current?.statusCode ?? "", latest?.plannedSubmissionDate?.toISOString() ?? "", current?.issueDate?.toISOString() ?? "",
      current?.releasedAt?.toISOString() ?? "", approval?.approverName ?? "", run?.templateName ?? "", run?.status ?? "",
      String(d._count.baselineEntries), String(d._count.packageMembers), d.updatedAt.toISOString(),
    ]);
  }
  const csv = rows.map((r) => r.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n");
  return new NextResponse(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="register-view-${stamp.toISOString().slice(0, 16).replaceAll(":", "")}.csv"`,
    },
  });
}
