# Windows version of deploy/init-env.sh: creates deploy/.env with a random
# password for every service, once. Never commit that file.
#
#   powershell -ExecutionPolicy Bypass -File deploy\init-env.ps1
#
# If the .NET SDK is installed, it also stores the same credentials as
# user-secrets for `dotnet run`, outside the repository.
$ErrorActionPreference = 'Stop'
$envFile = Join-Path $PSScriptRoot '.env'

function New-Secret {
    $chars = [char[]]'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    # Works in Windows PowerShell 5.1 as well as PowerShell 7.
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
}

if (Test-Path $envFile) {
    Write-Host "$envFile exists; nothing changed."
} else {
    $lines = @(
        '# Generated by deploy/init-env.ps1. Never commit this file.'
        "POSTGRES_SUPERUSER_PASSWORD=$(New-Secret)"
        "DB_APP_PASSWORD=$(New-Secret)"
        "DB_MONITOR_PASSWORD=$(New-Secret)"
        "DB_REPLICATION_PASSWORD=$(New-Secret)"
        "RABBITMQ_PASSWORD=$(New-Secret)"
        'STORAGE_ACCESS_KEY=delios'
        "STORAGE_SECRET_KEY=$(New-Secret)"
        "GRAFANA_ADMIN_PASSWORD=$(New-Secret)"
    )
    # Unix line endings and no byte-order mark: Docker Compose reads this file.
    [System.IO.File]::WriteAllText($envFile, ($lines -join "`n") + "`n")
    Write-Host "Created $envFile"
}

if (Get-Command dotnet -ErrorAction SilentlyContinue) {
    $values = @{}
    Get-Content $envFile | Where-Object { $_ -match '^\s*([A-Z_]+)=(.*)$' } | ForEach-Object { $values[$Matches[1]] = $Matches[2] }
    $project = Join-Path $PSScriptRoot '..\backend\src\Delios.Host'
    $secrets = [ordered]@{
        'ConnectionStrings:Postgres' = "Host=localhost;Port=5432;Database=delios;Username=delios;Password=$($values.DB_APP_PASSWORD)"
        'ConnectionStrings:RabbitMq' = "amqp://delios:$($values.RABBITMQ_PASSWORD)@localhost:5672/"
        'Storage:AccessKey' = $values.STORAGE_ACCESS_KEY
        'Storage:SecretKey' = $values.STORAGE_SECRET_KEY
    }
    foreach ($key in $secrets.Keys) {
        dotnet user-secrets set $key $secrets[$key] --project $project | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "dotnet user-secrets failed for $key" }
    }
    Write-Host 'Stored the same credentials as user-secrets for dotnet run.'
}
