#!/bin/sh
# Creates deploy/.env with a random password for every service, once. The file
# is never committed; Compose reads it on every command. Run it again and it
# leaves an existing file alone.
#
#   sh deploy/init-env.sh
#
# If the .NET SDK is installed, it also stores the same credentials as
# user-secrets for `dotnet run`, outside the repository.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
env_file="$here/.env"

random() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32; }

if [ -f "$env_file" ]; then
  echo "$env_file exists; nothing changed."
else
  umask 077
  cat > "$env_file" <<ENV
# Generated by deploy/init-env.sh. Never commit this file.
POSTGRES_SUPERUSER_PASSWORD=$(random)
DB_APP_PASSWORD=$(random)
DB_MONITOR_PASSWORD=$(random)
DB_REPLICATION_PASSWORD=$(random)
RABBITMQ_PASSWORD=$(random)
STORAGE_ACCESS_KEY=delios
STORAGE_SECRET_KEY=$(random)
GRAFANA_ADMIN_PASSWORD=$(random)
ENV
  echo "Created $env_file"
fi

if command -v dotnet >/dev/null 2>&1; then
  # shellcheck disable=SC1090
  . "$env_file"
  project="$here/../backend/src/Delios.Host"
  dotnet user-secrets set "ConnectionStrings:Postgres" \
    "Host=localhost;Port=5432;Database=delios;Username=delios;Password=$DB_APP_PASSWORD" --project "$project" >/dev/null
  dotnet user-secrets set "ConnectionStrings:RabbitMq" \
    "amqp://delios:$RABBITMQ_PASSWORD@localhost:5672/" --project "$project" >/dev/null
  dotnet user-secrets set "Storage:AccessKey" "$STORAGE_ACCESS_KEY" --project "$project" >/dev/null
  dotnet user-secrets set "Storage:SecretKey" "$STORAGE_SECRET_KEY" --project "$project" >/dev/null
  echo "Stored the same credentials as user-secrets for dotnet run."
fi
