// Run from the repo root: node scripts/gen-theme.mjs
// Generates src/app/theme.css: light tokens, a dark override of the Tailwind
// palettes in use, and a "palette-light" scope that restores light values
// (for the always-dark sidebar).
import fs from "node:fs";
const root = process.cwd();
const theme = fs.readFileSync(`${root}/node_modules/tailwindcss/theme.css`, "utf8");
const val = {};
for (const m of theme.matchAll(/--color-([a-z]+)-(\d+):\s*([^;]+);/g)) (val[m[1]] ??= {})[m[2]] = m[3].trim();

const SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
const HUES = ["red", "orange", "amber", "yellow", "lime", "green", "emerald", "teal", "cyan", "sky", "blue", "indigo", "violet", "purple", "fuchsia", "pink", "rose"];
const BG = "#111823";
const mix = (c, pct) => `color-mix(in oklab, ${c} ${pct}%, ${BG})`;
// Pale tints become deep tints; deep inks become pale inks; mid tones stay.
const darkHue = (h) => ({
  50: mix(val[h][900], 22), 100: mix(val[h][900], 36), 200: mix(val[h][800], 52), 300: val[h][700],
  400: val[h][500], 500: val[h][400], 600: val[h][500], 700: val[h][300], 800: val[h][200], 900: val[h][100], 950: val[h][50],
});
const darkNeutral = {
  50: "#161e2b", 100: "#1d2636", 200: "#2a3547", 300: "#3a475c", 400: "#64738a", 500: "#8795a9",
  600: "#a2adbd", 700: "#c0c9d5", 800: "#d9dfe7", 900: "#e9edf2", 950: "#f5f7fa",
};
const NEUTRALS = ["slate", "gray", "zinc"];

// Light is its own design, not the dark theme with the lamps turned up. The
// canvas is a cool grey the white surface can sit on and be seen; the hairline
// is one token, so every rule in the app is the same weight; the inks step
// evenly from the page to the strongest text.
const brandLight = {
  surface: "#ffffff", canvas: "#eceff4", "canvas-deep": "#e2e7ee",
  line: "#d7dde6", "line-strong": "#bcc6d4",
  brand: "#1e3a5f", "brand-hover": "#2d5480", "brand-strong": "#17324d", "brand-ink": "#1e3a5f",
  "brand-line": "#3b6389", link: "#2b5b80", tint: "#e4eef7", "tint-soft": "#f2f6fb",
};
const brandDark = {
  surface: BG, canvas: "#0a0f17", "canvas-deep": "#070b12",
  line: "#273245", "line-strong": "#37455c",
  brand: "#2f5e8e", "brand-hover": "#3a70a6", "brand-strong": "#28527d", "brand-ink": "#c6d9ec",
  "brand-line": "#5f8fbf", link: "#8db8de", tint: "#1a2a3c", "tint-soft": "#152131",
};
const decl = (o, prefix = "--color-") => Object.entries(o).map(([k, v]) => `  ${prefix}${k}: ${v};`).join("\n");

let out = `/* Generated by scripts/gen-theme.mjs — do not edit by hand. */\n\n`;
out += `@theme {\n${decl(brandLight)}\n}\n\n`;
// Light mode says so out loud. Left unsaid, the browser follows the operating
// system, and a machine set to dark draws its own cursors, scrollbars and
// native controls over a light page — a white resize cursor on white paper.
out += `:root {\n  color-scheme: light;\n}\n\n`;
const dark = [];
for (const [k, v] of Object.entries(brandDark)) dark.push(`  --color-${k}: ${v};`);
for (const n of NEUTRALS) for (const s of SHADES) dark.push(`  --color-${n}-${s}: ${darkNeutral[s]};`);
for (const h of HUES) { const d = darkHue(h); for (const s of SHADES) dark.push(`  --color-${h}-${s}: ${d[s]};`); }
out += `:root.dark {\n  color-scheme: dark;\n${dark.join("\n")}\n}\n\n`;
const light = [];
for (const [k, v] of Object.entries(brandLight)) light.push(`  --color-${k}: ${v};`);
for (const n of [...NEUTRALS, ...HUES]) for (const s of SHADES) light.push(`  --color-${n}-${s}: ${val[n][s]};`);
out += `/* Always-dark chrome (the sidebar) keeps the light palette in both themes. */\n:root.dark .palette-light {\n  color-scheme: light;\n${light.join("\n")}\n}\n`;
fs.writeFileSync(`${root}/src/app/theme.css`, out);
console.log("ok", out.length);
